export const ABOUT_FETCH_REQUEST = 'ABOUT_FETCH_REQUEST';
export const ABOUT_FETCH_SUCCESS = 'ABOUT_FETCH_SUCCESS';
export const ABOUT_FETCH_FAIL = 'ABOUT_FETCH_FAIL';
export const ABOUT_UPDATE_REQUEST = 'ABOUT_UPDATE_REQUEST';
export const ABOUT_UPDATE_SUCCESS = 'ABOUT_UPDATE_SUCCESS';
export const ABOUT_UPDATE_FAIL = 'ABOUT_UPDATE_FAIL';
