export const GET_HOME_CONTACT_REQUEST = "GET_HOME_CONTACT_REQUEST";
export const GET_HOME_CONTACT_SUCCESS = "GET_HOME_CONTACT_SUCCESS";
export const GET_HOME_CONTACT_FAIL = "GET_HOME_CONTACT_FAIL";

export const UPDATE_HOME_CONTACT_REQUEST = "UPDATE_HOME_CONTACT_REQUEST";
export const UPDATE_HOME_CONTACT_SUCCESS = "UPDATE_HOME_CONTACT_SUCCESS";
export const UPDATE_HOME_CONTACT_FAIL = "UPDATE_HOME_CONTACT_FAIL";
