export const GET_ABOUT_CONTENT_SUCCESS = "GET_ABOUT_CONTENT_SUCCESS";
export const GET_ABOUT_CONTENT_FAILURE = "GET_ABOUT_CONTENT_FAILURE";
export const UPDATE_ABOUT_CONTENT_SUCCESS = "UPDATE_ABOUT_CONTENT_SUCCESS";
export const UPDATE_ABOUT_CONTENT_FAILURE = "UPDATE_ABOUT_CONTENT_FAILURE";
