export const GET_HOMEPAGE_CONTENT_SUCCESS = 'GET_HOMEPAGE_CONTENT_SUCCESS';
export const GET_HOMEPAGE_CONTENT_FAILURE = 'GET_HOMEPAGE_CONTENT_FAILURE';
export const UPDATE_HOMEPAGE_CONTENT_SUCCESS = 'UPDATE_HOMEPAGE_CONTENT_SUCCESS';
export const UPDATE_HOMEPAGE_CONTENT_FAILURE = 'UPDATE_HOMEPAGE_CONTENT_FAILURE';