export const SERVICE_LIST_REQUEST = 'SERVICE_LIST_REQUEST';
export const SERVICE_LIST_SUCCESS = 'SERVICE_LIST_SUCCESS';
export const SERVICE_LIST_FAIL = 'SERVICE_LIST_FAIL';

export const SERVICE_CREATE_REQUEST = 'SERVICE_CREATE_REQUEST';
export const SERVICE_CREATE_SUCCESS = 'SERVICE_CREATE_SUCCESS';
export const SERVICE_CREATE_FAIL = 'SERVICE_CREATE_FAIL';
